Header header

string head

string calculateStatus	
string locateStatus		
float64 baseLine				
float64 yawAngle 			
float64 pitchAngle		
float64 yuLiu1			
float64 yawAngleError		
float64 pitchAngleError		
string rtkID			
int16 satelliteTrackNum	
int16 satelliteCalculateNum	
int16 satelliteHighNum		
int16 satelliteL2Num		
int16 yuLiu2				
int16 expandCalculateStatus  
int16 yuLiu3				
int16 signalMaskStatus    	
